<a href="https://colab.research.google.com/github/RinayGajjar/Car_Price_Prediction/blob/main/CarPricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('cardekho_imputated.csv')

In [4]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [6]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [8]:
df.drop(['car_name','brand'],inplace = True,axis = 1)

In [9]:
df

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [10]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [12]:
numerical_features = [features for features in df.columns if df[features].dtype!='object']
numerical_features

['Unnamed: 0',
 'vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [13]:
categorical_features = [features for features in df.columns if df[features].dtype=='object']
categorical_features

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [14]:
discrete_feature = [feature for feature in numerical_features if len(df[feature].unique())<25]
discrete_feature

['vehicle_age', 'seats']

In [15]:
continuous_feature = [feature for feature in numerical_features if feature not in discrete_feature]
continuous_feature

['Unnamed: 0', 'km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [16]:
X = df.drop('selling_price',axis = 1)
Y = df['selling_price']

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [19]:
X['model'].value_counts()

model
118    906
89     890
88     781
7      778
25     757
      ...
51       1
8        1
50       1
12       1
55       1
Name: count, Length: 120, dtype: int64

In [21]:
X.head()

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [24]:
len(X['fuel_type'].value_counts()),len(X['seller_type'].value_counts()),len(X['transmission_type'].value_counts())

(5, 3, 2)

In [25]:
num_features = X.select_dtypes(exclude = 'object').columns
cat_features = X.select_dtypes(include = 'object').columns

In [27]:
one_hot_Columns = ['fuel_type','transmission_type','seller_type']

In [35]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop = 'first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, one_hot_Columns),
        ("StandardScaler", numeric_transformer, num_features),
    ],remainder = 'passthrough'##means other features will be as it is only cat features will change
)

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)

In [37]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [51]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [52]:
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'KNeighborsRegressor':KNeighborsRegressor(),
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'RandomForestRegressor':RandomForestRegressor()
}

In [63]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,Y_train)

    y_pred_test = model.predict(X_test)
    y_pred_train = model.predict(X_train)
    mae_test, rmse_test, r2_square_test=evaluate_model(Y_test,y_pred)
    mae_train, rmse_train, r2_square_train = evaluate_model(Y_train,y_pred_train)
    print(list(models.keys())[i])

    print('---------------------------------')

    print('model performance of training dataset')
    print('mae',mae_train)
    print('rmse',rmse_train)
    print('r2_square',r2_square_test*100)

    print('---------------------------------')

    print('model performance of testing dataset')
    print('mae',mae_test)
    print('rmse',rmse_test)
    print('r2_square',r2_square_test*100)

LinearRegression
---------------------------------
model performance of training dataset
mae 268104.130255497
rmse 553850.0493563744
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643
Lasso
---------------------------------
model performance of training dataset
mae 268101.7550054886
rmse 553850.0537694937
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643
Ridge
---------------------------------
model performance of training dataset
mae 268061.6556874922
rmse 553850.6939435791
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643
KNeighborsRegressor
---------------------------------
model performance of training dataset
mae 97678.9746917586
rmse 335516.72788664146
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643
DecisionTreeRegressor
---------------------------------
model performance of training dataset
mae 0.0
rmse 0.0
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643
RandomForestRegressor
---------------------------------
model performance of training dataset
mae 36652.74091499027
rmse 147746.789839277
r2_square 92.60996715080643
---------------------------------
model performance of testing dataset
mae 97965.35679532922
rmse 235861.86974468065
r2_square 92.60996715080643

In [64]:
knn_params = {"n_neighbors":[2,3,4,5,6,7,8,9,10]}
rf_params = {"n_estimators":[100,200,500,1000],
             "max_depth":[3,5,7,10],
             "max_features":['auto',5,7,9],
             "min_samples_split":[2,5,10]}

In [65]:
random_cv = [('KNN',KNeighborsRegressor(),knn_params),
             ('RF',RandomForestRegressor(),rf_params)]

In [66]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
model_param = {}
for name,model,params in random_cv:
  random = RandomizedSearchCV(estimator = model,
                            param_distributions = params,
                            n_iter = 100,
                            cv = 3,
                            verbose = 2,
                            n_jobs = -1)
  random.fit(X_train,Y_train)
  model_param[name] = random.best_params_

Fitting 3 folds for each of 9 candidates, totalling 27 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits